### ISSUE TITLE
Get RingGroup Status

### ISSUE THREAD

**Issue by MSProgrammer** [rillian/asterisk-opus#3]
Hi guys 
Can I  Get RingGroup Status Like QueueStatusAction , with ResponseEvent ?

I want to Take Details Like RingGroup Exten , Member Of Ring Group , Status and .....

with ResponseEvent

**Comment by rillian** [comment]
Sorry, I've no idea about this. Are you asking specifically about the Opus codec integration? Otherwise you might try the main repo at [asterisk/asterisk](https://github.com/asterisk/asterisk).

**Comment by MSProgrammer** [comment]
Thank you @rillian , I have turn it Around , but its not standard. I must to try it for a best way

**Comment by rillian** [comment]
Sorry, I've no idea about this. Are you asking specifically about the Opus codec integration? Otherwise you might try the main repo at [asterisk/asterisk](https://github.com/asterisk/asterisk).
